FROM python:3.11-slim as base

WORKDIR /app
COPY Pipefile Pipfile.lock /app/

RUN pip install pipenv

###

FROM base as develop

RUN pipen install

COPY app.py .
COPY Taskfile .

EXPOSE 8000
CMD ["gunicorn", "-c", "conf/gunicorn.conf.py", "app:app"]